apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-esac
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-erds-tenant/quarkus/devfile-sample-code-with-quarkus-esac@sha256:bee128259c9e6b45abb6151aefa4281fe321acd690f465e955eebfb6419a462a
        name: my-java-quarkus
        resources: {}
status: {}
